version: '3.7'
services:
  server:
    build:
      context: server
      dockerfile: Dockerfile
    environment:
      # - NODE_ENV=production
      - "MONGODB_URI=mongodb://mongo:27017/trackr"
      - "PORT=3000"
      - "MONGO_INITDB_DATABASE=trackr"
    # volumes:
    #  - ./server/:/app
    # user: "${UID}:${GID}"
    ports:
        - "3000:3000"
    restart: "unless-stopped"
    depends_on:
      - mongo
  client:
    build:
      context: client
      dockerfile: Dockerfile
#    environment:
#      - NODE_ENV=production
#      - PORT=8080
    ports:
        - "8080:8080"
    restart: "unless-stopped"
  mongo:
    image: mongo:5.0
    restart: "unless-stopped"
#    user: "${UID}:${GID}"
    volumes:
      - ./data/mongo:/data/db
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
        - "27017:27017"
