# This is a basic workflow to help you get started with Actions

name: Unit Tests Backend

# Controls when the workflow will run
on:
  pull_request:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  unit_test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Git checkout
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      uses: actions/checkout@v2

    - name: Use Node.js 17
      uses: actions/setup-node@v2
      with:
        node-version: 17

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.7.0
      with:
        mongodb-version: 5.0

    # Runs a set of commands using the runners shell
    - run: |
        cd server
        npm ci
        npm run build
        npm run test
